In [2]:
#practise git lab and dimensions
import numpy as np

In [39]:
#refer google collab file for np basics
#np.array()
#popoulation,sample
print(np.random.seed(70)) # here seed  is for only that session also acts like random state
np.random.rand()

None


0.9274805386189587

In [45]:
np.random.rand(10)

array([0.29985244, 0.41653714, 0.49416956, 0.18474801, 0.14292333,
       0.10897001, 0.44114742, 0.82993661, 0.94672854, 0.53469047])

In [93]:
np.random.rand()

0.4892605657527902

In [77]:
np.random.randint(11)

8

In [35]:
np.random.random(10)

array([0.9971389 , 0.91571142, 0.88728813, 0.25997727, 0.29265939,
       0.69883433, 0.58763582, 0.41393578, 0.93088313, 0.08549361])

In [92]:
np.random.random()

0.8944395952771839

In [95]:
np.random.choice([1,2,3],size=3,replace=True)

array([2, 3, 3])

In [96]:
data=np.random.randint(0,5,size=(4,3))
data

array([[4, 4, 2],
       [0, 2, 2],
       [2, 0, 4],
       [3, 2, 4]], dtype=int32)

In [97]:
data.mean()

np.float64(2.4166666666666665)

In [98]:
data.mean(axis=0)

array([2.25, 2.  , 3.  ])

In [99]:
data.mean(axis=1)

array([3.33333333, 1.33333333, 2.        , 3.        ])

In [100]:
data.var()

np.float64(1.9097222222222225)

In [101]:
arr2=np.random.randint(2,20,[6,6])

In [102]:
arr2

array([[10,  4,  3,  2, 18, 12],
       [17, 16,  4, 14, 13, 18],
       [ 2, 17, 17,  5, 11,  3],
       [ 5, 17,  8, 15,  9, 18],
       [15, 19,  5,  4, 18,  7],
       [16, 18, 19, 18, 16, 17]], dtype=int32)

In [103]:
arr2[3:5,0:4]

array([[ 5, 17,  8, 15],
       [15, 19,  5,  4]], dtype=int32)

In [104]:
arr2[:,4:6]

array([[18, 12],
       [13, 18],
       [11,  3],
       [ 9, 18],
       [18,  7],
       [16, 17]], dtype=int32)

In [107]:
arr2[:,[1,3,4]]

array([[ 4,  2, 18],
       [16, 14, 13],
       [17,  5, 11],
       [17, 15,  9],
       [19,  4, 18],
       [18, 18, 16]], dtype=int32)

In [ ]:
arr2[:,1]=arr2[:,2]+10 #STAR

In [110]:
arr2[:,1]

array([13, 14, 27, 18, 15, 29], dtype=int32)

In [112]:
arr2

array([[10, 13,  3,  2, 18, 12],
       [17, 14,  4, 14, 13, 18],
       [ 2, 27, 17,  5, 11,  3],
       [ 5, 18,  8, 15,  9, 18],
       [15, 15,  5,  4, 18,  7],
       [16, 29, 19, 18, 16, 17]], dtype=int32)

In [111]:
arr2.T

array([[10, 17,  2,  5, 15, 16],
       [13, 14, 27, 18, 15, 29],
       [ 3,  4, 17,  8,  5, 19],
       [ 2, 14,  5, 15,  4, 18],
       [18, 13, 11,  9, 18, 16],
       [12, 18,  3, 18,  7, 17]], dtype=int32)

In [120]:
arr2

array([[10, 13,  3,  2, 18, 12],
       [17, 14,  4, 14, 13, 18],
       [ 2, 27, 17,  5, 11,  3],
       [ 5, 18,  8, 15,  9, 18],
       [15, 15,  5,  4, 18,  7],
       [16, 29, 19, 18, 16, 17]], dtype=int32)

In [119]:
a=arr2[::-1,]
a

array([[16, 29, 19, 18, 16, 17],
       [15, 15,  5,  4, 18,  7],
       [ 5, 18,  8, 15,  9, 18],
       [ 2, 27, 17,  5, 11,  3],
       [17, 14,  4, 14, 13, 18],
       [10, 13,  3,  2, 18, 12]], dtype=int32)

In [121]:
b=arr2[::-1]
b

array([[16, 29, 19, 18, 16, 17],
       [15, 15,  5,  4, 18,  7],
       [ 5, 18,  8, 15,  9, 18],
       [ 2, 27, 17,  5, 11,  3],
       [17, 14,  4, 14, 13, 18],
       [10, 13,  3,  2, 18, 12]], dtype=int32)

In [123]:
c=arr2[::-1,::-1]
c

array([[17, 16, 18, 19, 29, 16],
       [ 7, 18,  4,  5, 15, 15],
       [18,  9, 15,  8, 18,  5],
       [ 3, 11,  5, 17, 27,  2],
       [18, 13, 14,  4, 14, 17],
       [12, 18,  2,  3, 13, 10]], dtype=int32)

In [133]:
f=arr2.flatten()
f

array([10,  0,  3,  2, 18, 12, 17, 14,  4, 14, 13, 18,  2, 27, 17,  5, 11,
        3,  5, 18,  8, 15,  9, 18, 15, 15,  5,  4, 18,  7, 16, 29, 19, 18,
       16, 17], dtype=int32)

In [134]:
r=arr2.ravel()
r 

array([10,  0,  3,  2, 18, 12, 17, 14,  4, 14, 13, 18,  2, 27, 17,  5, 11,
        3,  5, 18,  8, 15,  9, 18, 15, 15,  5,  4, 18,  7, 16, 29, 19, 18,
       16, 17], dtype=int32)

In [135]:
f[1]=10
f

array([10, 10,  3,  2, 18, 12, 17, 14,  4, 14, 13, 18,  2, 27, 17,  5, 11,
        3,  5, 18,  8, 15,  9, 18, 15, 15,  5,  4, 18,  7, 16, 29, 19, 18,
       16, 17], dtype=int32)

In [136]:
r[1]=20
r

array([10, 20,  3,  2, 18, 12, 17, 14,  4, 14, 13, 18,  2, 27, 17,  5, 11,
        3,  5, 18,  8, 15,  9, 18, 15, 15,  5,  4, 18,  7, 16, 29, 19, 18,
       16, 17], dtype=int32)

In [137]:
f

array([10, 10,  3,  2, 18, 12, 17, 14,  4, 14, 13, 18,  2, 27, 17,  5, 11,
        3,  5, 18,  8, 15,  9, 18, 15, 15,  5,  4, 18,  7, 16, 29, 19, 18,
       16, 17], dtype=int32)

In [139]:
r

array([10, 20,  3,  2, 18, 12, 17, 14,  4, 14, 13, 18,  2, 27, 17,  5, 11,
        3,  5, 18,  8, 15,  9, 18, 15, 15,  5,  4, 18,  7, 16, 29, 19, 18,
       16, 17], dtype=int32)

In [140]:
arr2

array([[10, 20,  3,  2, 18, 12],
       [17, 14,  4, 14, 13, 18],
       [ 2, 27, 17,  5, 11,  3],
       [ 5, 18,  8, 15,  9, 18],
       [15, 15,  5,  4, 18,  7],
       [16, 29, 19, 18, 16, 17]], dtype=int32)

In [10]:
import numpy as np
n=np.arange(10)
b=n.astype(float)

In [12]:
b[3]= np.nan
b

array([ 0.,  1.,  2., nan,  4.,  5.,  6.,  7.,  8.,  9.])

In [13]:
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
type(np.nan)

float

In [15]:
np.isnan(b)

array([False, False, False,  True, False, False, False, False, False,
       False])

In [18]:
n[n>2]# gives actual values

array([3, 4, 5, 6, 7, 8, 9])

In [20]:
np.where(n>5)# gives index

(array([6, 7, 8, 9]),)

In [23]:
np.where(n>5,'G5','L5')

array(['L5', 'L5', 'L5', 'L5', 'L5', 'L5', 'G5', 'G5', 'G5', 'G5'],
      dtype='<U2')

In [25]:
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.where(n>5,'l5',np.where(n<2,'l2','g2')) # multiple conditions 

array(['l2', 'l2', 'g2', 'g2', 'g2', 'g2', 'l5', 'l5', 'l5', 'l5'],
      dtype='<U2')

In [ ]:
#concat,hstack,vstack,cbind,rbind

In [33]:
n1=np.array([[1,2,3],[4,5,6]])
n2=np.array([[11,12,13],[14,15,16]])

In [34]:
np.concatenate([n1,n2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [35]:
np.concatenate([n1,n2],axis=1)

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [36]:
np.hstack([n1,n2])

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [37]:
np.vstack([n1,n2])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [38]:
np.c_[n1,n2]

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16]])

In [39]:
np.r_[n1,n2]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [49]:
n3=np.random.rand(3,3)
n3

array([[0.35851764, 0.03788512, 0.67371578],
       [0.06788386, 0.63421245, 0.99115586],
       [0.93417392, 0.56880643, 0.01086408]])

In [50]:
np.sort(n3,axis=0)

array([[0.06788386, 0.03788512, 0.01086408],
       [0.35851764, 0.56880643, 0.67371578],
       [0.93417392, 0.63421245, 0.99115586]])

In [51]:
np.sort(n3,axis=1)

array([[0.03788512, 0.35851764, 0.67371578],
       [0.06788386, 0.63421245, 0.99115586],
       [0.01086408, 0.56880643, 0.93417392]])

In [63]:
n4=np.random.randint(1,10,size=(3,3))
n4

array([[1, 7, 7],
       [1, 2, 7],
       [9, 4, 5]], dtype=int32)

In [64]:
np.mean(n4,axis=1)

array([5.        , 3.33333333, 6.        ])

In [65]:
np.mean(n4,axis=0)

array([3.66666667, 4.33333333, 6.33333333])

In [67]:
np.argsort(n4,axis=0) #returns array index not the data

array([[0, 1, 2],
       [1, 2, 0],
       [2, 0, 1]])

In [68]:
np.argsort(n4,axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [1, 2, 0]])

In [69]:
n4[np.argsort(n4,axis=1)]#STAR NOT TAUGHT

array([[[1, 7, 7],
        [1, 2, 7],
        [9, 4, 5]],

       [[1, 7, 7],
        [1, 2, 7],
        [9, 4, 5]],

       [[1, 2, 7],
        [9, 4, 5],
        [1, 7, 7]]], dtype=int32)

In [82]:
n5=np.random.randint(1,10,size=(2,2))
n5

array([[2, 3],
       [1, 5]], dtype=int32)

In [83]:
n5[:,0]

array([2, 1], dtype=int32)

In [84]:
sorted_index=n5[:,0].argsort()
sorted_index 

array([1, 0])

In [85]:
n5[sorted_index]

array([[1, 5],
       [2, 3]], dtype=int32)

In [86]:
n4

array([[1, 7, 7],
       [1, 2, 7],
       [9, 4, 5]], dtype=int32)

In [88]:
lexsorted_index=np.lexsort((n4[:,1],n4[:,2]))
lexsorted_index #1 2 0, 2 1 0

array([2, 1, 0])

In [89]:
n4[lexsorted_index]

array([[9, 4, 5],
       [1, 2, 7],
       [1, 7, 7]], dtype=int32)

In [90]:
lexsorted_index1=np.lexsort((n4[:,2],n4[:,1]))
lexsorted_index1 #1 2 0, 2 1 0 

array([1, 2, 0])

In [91]:
n4[lexsorted_index1]

array([[1, 2, 7],
       [9, 4, 5],
       [1, 7, 7]], dtype=int32)

In [92]:
sorted_index2=n4[:,1].argsort()
sorted_index2 

array([1, 2, 0])

In [93]:
n4[sorted_index2]

array([[1, 2, 7],
       [9, 4, 5],
       [1, 7, 7]], dtype=int32)

In [110]:
n6=np.random.randint(1,10,size=(5,5))
n6

array([[5, 1, 6, 3, 8],
       [7, 1, 7, 1, 4],
       [2, 5, 2, 8, 1],
       [6, 1, 3, 3, 6],
       [6, 8, 6, 1, 4]], dtype=int32)

In [111]:
lexsorted_index6=np.lexsort((n6[0,:],n6[1,:]))
lexsorted_index6

array([1, 3, 4, 0, 2])

In [112]:
n6[lexsorted_index6] 

array([[7, 1, 7, 1, 4],
       [6, 1, 3, 3, 6],
       [6, 8, 6, 1, 4],
       [5, 1, 6, 3, 8],
       [2, 5, 2, 8, 1]], dtype=int32)

In [113]:
n6[ : ,lexsorted_index6]  

array([[1, 3, 8, 5, 6],
       [1, 1, 4, 7, 7],
       [5, 8, 1, 2, 2],
       [1, 3, 6, 6, 3],
       [8, 1, 4, 6, 6]], dtype=int32)